{% set version = '1.3.3' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-tibble
  version: {{ version|replace("-", "_") }}

source:
  fn: tibble_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/tibble_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/tibble/tibble_{{ version }}.tar.gz
  sha256: 802ec8346eae2397a2fc64b254cf80a67c7832cb5211328336f45053ea2518ae

build:
  number: 0
  skip: true  # [win32]

  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - r-base
    - r-rcpp >=0.12.3
    - r-rlang
    - r-lazyeval >=0.1.10
    - posix                # [win]
    - {{native}}toolchain  # [win]
    - gcc                  # [not win]

  run:
    - r-base
    - r-rcpp >=0.12.3
    - r-rlang
    - libgcc  # [not win]

test:
  commands:
    - $R -e "library('tibble')"  # [not win]
    - "\"%R%\" -e \"library('tibble')\""  # [win]

about:
  home: https://github.com/tidyverse/tibble
  license: MIT
  summary: Provides a 'tbl_df' class that offers better checking and printing capabilities than
    traditional data frames.
  license_family: MIT

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
