travis:
  secure:
    BINSTAR_TOKEN: fgb39T415hGZAC96kGBr98Mmq5dOfu6icTfAymx/x+16Yd2Yur7kY978UUnbHpjpN6CeXm2hR2TJxpy6fhcHcpCcicmmn5qLAiu/uAbnMJXlAJepaUWrTpnL6mQl+P42fda7hm4yOiXuI7CNACtwDHWzjaQYJc7BHjOqmnEr1Hi7OHUqTBdQ12Zy1THaGQLfppoZ9SMS/ynN3ldxxKaITjo8nMktRUKQBTIGHAO3VXKNnXdTGMFYVDfNd33bKpaDN3e8MiJ1psOJpztYFUDn8I6skYvYnRJc+I016Q7vY4ZR8jRlXWQX/Z9tBxS+sDirXmyLLgs/HecplM9xZu5zg3Rh9fdYE/YOGNHKbWkRi4oXyVa3qs+gI/wT7YmcJpVn3Cw4bkT1vCLLWmmy67Sxz/S7AtZ+DIMkYhgH7KAzcBetBA+ouoJOBm8JG56p1uhFofNn13J+NHYTu8T2S00r+p6khlUHdErtuE0ygUDZU+dDfnRGttstvxlSH8CfzI8KlFZdWGslqHWxyIb+0K1kMhdpAxDTlntwk6UUlRSZayj1vGaDXXz8OrQA1vkvw7HXBV8W9HgHVIwtwQq09NRoksd3f1k4yH2ADUAQP1I6vm9z8L56d7TpWbduwtWGrEOYZ1S7UsqjkpkOsEYtH8nYN+cwkfj5k/btsNIlM8khPps=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
