travis:
  secure:
    BINSTAR_TOKEN: N0iXFRmGYhriex7hrVapLtzk9NwkN0UyCqhTvv/1LuxgD0ArghiYS/crDIjaBPhBt/VZ8juPaHSLal+/U4AFMk2LWwpm1SZPfCAOsWDMnxokWXhIedVuIUPF+zHp2QimT4G3m5xfUctkVCTfufN7cMvYOdlnSz0dfeYe9cVNScjGgg5oEZcRFWh/dvdt0pow7gCC30m2EtIKYlP0j4us+ujrmwLBM9sGn67DRm2s2rIuiDA9UoOSUvZQYhlHSPQT0rvSRI439yFKNiXMLH49NmJJcDGyHh9to1gvQIHJ1VYi5iw7xKskL5NjXIKvWKGRgS5eTtmOb1q2amkn8i7Lwdx0VtQN6KrIeaOA1qSFGfsuIuT9yWvbVdchgVvXAhWNEndaVk+zUyZJohnIR4+QEcqD9h8iyFNSJ0l6kN4BWp1qLbjWtRmXyUYaZZFFVI70GnDFJScVQ4aoE0TX7rxyiuKhEvcasaS5IJas/d9wu7OCdrcEmfh15VzrV8vgo1LjnfCKSnvttXnwrsUgTTabJBy7fAuUN4Lk1vofURDk7CR6+slP3R2FB65NIMdNwKpnmKAt2PMuht9BmGY0AGqsDAJygVKkbudKVweDTDPa5ywKRQzOva7CTizOASej7EukwSS+Vb5SauMUF2UhvgfnoGf+wQK/E+9VGnoAmae6SaI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
